psigc/psigccon/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from psigccon import views

urlpatterns = [
    path('', views.vista_conocim, name='url_conocim'),
    path('url_mapindicad', views.vista_mapindicad, name='url_mapindicad'),
    path('url_mapindice', views.vista_mapindice, name='url_mapindice'),
    
]

psigc/psigchom/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from psigchom import views
from .views import vista_contacto, vista_loginUser, vista_registUser, vista_getmunics, vista_proceden

urlpatterns = [
    path('',views.vista_inicio, name='url_inicio'),
    path('url_ayuda/', views.vista_codayuda, name='url_ayuda'),
    path('url_codigo/', views.vista_codayuda, name='url_codigo'),
    path('url_registuser/',vista_registUser.as_view(), name='url_registuser'),
    path('url_loginuser/', views.vista_loginUser, name='url_loginuser'),
    path('url_sideloginuser/', views.sidelogin_form, name='url_sideloginuser'),
    
    path('url_perfiluser/<int:id_user>', views.vista_PerfilUser, name='url_perfiluser'),
    path('url_updperfuser/', views.vista_PerfilUser, name='url_updperfuser'),

    path('url_logout/', views.vista_LogoutUser, name='url_logout'),
    path('url_contacto/', vista_contacto.as_view(), name='url_contacto'),

    path('url_proceden/', views.vista_proceden, name='url_proceden'),
    path('url_getmunics/', views.vista_getmunics, name='url_getmunics'),
]

psigc/psigcproy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('psigchom.urls')),
    path('url_redconoc/', include('psigcred.urls')),
    path('url_reportes/', include('psigcrep.urls')),
    path('url_conocim/', include('psigccon.urls')),
    path('url_basesdatos/', include('psigcmod.urls')),
    path('url_gestion/', include('psigcges.urls')),

]
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

psigc/psigchom/models.py
from django.db import models

# Create your models here.

psigc/psigcmod/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import AbstractUser, Group
from .choices import ctipodemand, cgenero, cgrd, ctiporg, cpais, cgrp, calcanc, cpublic
from django.core.exceptions import ValidationError

# Create your models here.

class Provincia(models.Model):
    idprov = models.AutoField(primary_key=True)
    nombreprov = models.CharField(max_length=100, unique=True)
    siglas = models.CharField(max_length=4, null=True, blank=True)

    def __str__(self) :
        return self.nombreprov
    
    class Meta:
        verbose_name ='Provincia'
        verbose_name_plural='Provincias'
        db_table ='provincia'
     
class Municipio(models.Model):
    idmun = models.AutoField(primary_key=True)
    nombremun = models.CharField(max_length = 100, unique=True)
    prov = models.ForeignKey("Provincia", on_delete=models.CASCADE)

    class Meta:
        verbose_name ='Municipio'
        verbose_name_plural ='Municipios'
        db_table ='municipio'

    def __str__(self) :
        return self.nombremun

class Procedencia(models.Model):
    provincia = models.OneToOneField("Provincia", on_delete=models.CASCADE, verbose_name='Provincia de procedencia*')
    municipio = models.OneToOneField("Municipio", on_delete=models.CASCADE, verbose_name='Municipio de procedencia*')

class ContactoBD(models.Model):
    idcontact = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length = 100, verbose_name="Nombre(s) y apellidos*")
    municipio = models.ForeignKey("Municipio", on_delete=models.SET_NULL, verbose_name='Municipio de procedencia', null=True, blank=True)
    ecorreo = models.EmailField(max_length = 100, verbose_name="Correo electrónico*")
    asunto = models.CharField(max_length = 200, verbose_name="Tema a tratar ")
    contenido = models.TextField(verbose_name="Contenido del mensaje")
    respuesta = models.TextField(verbose_name="Respuesta", null=True, blank=True)
    fechaenvio = models.DateField(auto_now_add=True,)

    class Meta:
        verbose_name ='Contactos enviado'
        verbose_name_plural='Contactos enviados'
        ordering = ['-fechaenvio']   
        db_table ='contacto'
    
    def __str__(self):
        return self.fechaenvio + " - " + self.nombre

class Grupo(Group):
    nombregrupo = models.CharField(max_length=20, choices=cgrp, verbose_name="Grupo de usuario", default='Invitados')
    class Meta:
        verbose_name= 'Grupo'
    def __str__(self):
        self = self.nombregrupo
        return self

class Usuario(AbstractUser):
    ingreso = models.DateField(auto_now_add=True,)
    municipio=models.ForeignKey("Municipio", on_delete=models.SET_NULL, verbose_name="Municipio de procedencia", blank=True, null=True)
    genero = models.CharField(max_length = 10, verbose_name="Género", choices=cgenero, null=True, default='')
    grdctfacad = models.CharField(max_length=20, choices=cgrd, verbose_name="Último título académico o científico alcanzado",blank=True, null=True)
    princresult = models.TextField(verbose_name="Principales resultados científicos", blank=True, null=True)
    foto=models.ImageField(default='', upload_to='Profiles', null=True, blank=True)
    grupo = models.ForeignKey("Grupo", verbose_name='Grupo de usuarios', on_delete=models.SET_NULL, null=True, blank=True)

    #activation_key = models.CharField(max_length=40, blank=True)
    #key_expires = models.DateTimeField(default=datetime.date.today())

    def __str__(self):
        self = self.last_name + " " + self.first_name + " (" + self.username + ")"
        return self

    class Meta: 
        verbose_name = 'Usuario'
        ordering = ['last_name', 'first_name',]
        db_table = 'usuario'

class AreaConocimiento(models.Model):
    idareaconoc = models.AutoField(primary_key=True)
    nombreareaconoc = models.CharField(max_length=100,verbose_name="Nombre del área ")
    descriparea= models.TextField(verbose_name="Descripción del tema ", null=True, blank=True, default='Descripción aún sin especificar')
    expertos = models.ManyToManyField("Usuario", verbose_name="Experto(s) en el tema", blank=True)

    class Meta:
        verbose_name = 'Área de conocimiento'
        verbose_name_plural = 'Áreas de conocimiento' 
        ordering = ['nombreareaconoc']   
        db_table ='areaconoc'
    
    def __str__(self) :
        return self.nombreareaconoc

class Oace(models.Model):
    idoace = models.AutoField(primary_key=True)
    siglas = models.CharField(max_length=10, verbose_name="Siglas", unique=True)
    nombreoace = models.CharField(max_length=60, verbose_name="Nombre del Organismo de Administración Central del Estado", unique=True)

    class Meta:
        verbose_name = 'Organismo del Estado'
        verbose_name_plural = 'Organismos del Estado' 
        ordering = ['nombreoace']   
        db_table ='oace'

    def __str__(self) :
        return self.nombreoace
    
    def save(self, *args, **kwargs):
        if  self.nombreoace == 'Ministerio de Ciencia, Tecnología y Medio Ambiente':
            self.siglas = 'CITMA'
        elif self.nombreoace == 'Ministerio del Comercio exterior e Inversión extranjera':
            self.siglas = 'MINCEX'
        elif self.nombreoace == 'Ministerio del Comercio Interior':
            self.siglas = 'MINCIN'
        elif self.nombreoace == 'Ministerio de Comunicaciones':
            self.siglas = 'MINCOM'
        elif self.nombreoace == 'Ministerio de Cultura':
            self.siglas = 'MINCULT'
        elif self.nombreoace == 'Ministerio de Educación':
            self.siglas = 'MINED'
        elif self.nombreoace == 'Ministerio de Educación Superior':
            self.siglas ='MES'
        elif self.nombreoace == 'Ministerio de Energía y Minas':
            self.siglas ='MINER'
        elif self.nombreoace == 'Ministerio de Finanzas y Precios':
            self.siglas = 'MFP'
        elif self.nombreoace == 'Ministerio de Industria Alimentaria':
            self.siglas = 'MINAL'
        elif self.nombreoace == 'Ministerio de Industrias':
            self.siglas = 'MINBAS'
        elif self.nombreoace == 'Ministerio de Justicia':
            self.siglas ='MINJUS'
        elif self.nombreoace == 'Ministerio de la Agricultura':
            self.siglas ='MINAG'
        elif self.nombreoace == 'Ministerio de la Construcción':
            self.siglas = 'MICONS'
        elif self.nombreoace == 'Ministerio de las Fuerzas Armadas':
            self.siglas = 'MINFAR'
        elif self.nombreoace == 'Ministerio de Relaciones Exteriores':
            self.siglas = 'MINREX'
        elif self.nombreoace == 'Ministerio de Salud Publica':
            self.siglas ='MINSAP'
        elif self.nombreoace == 'Ministerio de Transporte':
            self.siglas ='MITRANS'
        elif self.nombreoace == 'Ministerio de Turismo':
            self.siglas = 'MINTUR'
        elif self.nombreoace == 'Ministerio del Interior':
            self.siglas = 'MININT'
        elif self.nombreoace == 'Tribunal Supremo Popular':
            self.siglas = 'TSP'
        elif self.nombreoace == 'Banco Central de Cuba':
            self.siglas = 'BCC'
        elif self.nombreoace == 'Contraloría General de la República':
            self.siglas = 'CGR'
        elif self.nombreoace == 'Fiscalía General de la República':
            self.siglas = 'FGR'
        elif self.nombreoace == 'Instituto de Información y Comunicación Social':
            self.siglas = 'IICS'
        elif self.nombreoace == 'Instituto Nacional de Recursos Hidráulicos':
            self.siglas = 'INRH'
        elif self.nombreoace == 'Instituto Nacional de Deporte y Recreación':
            self.siglas ='INDER'
        elif self.nombreoace == 'Asamblea del Poder Popular (Gobierno)':
             self.siglas = 'APP'
        super(Oace, self).save(*args, **kwargs)

class ProgDesarrollo(models.Model):
    idprog = models.AutoField(primary_key=True)
    nombreprog = models.CharField(max_length=100, verbose_name="Nombre del programa de desarrollo", unique=True)
    descriprog = models.TextField(default="Descripción aún sin especificar", verbose_name="Descripción del programa", null=True, blank=True)
    oacerector = models.ForeignKey("Oace", verbose_name="Organismo rector",on_delete=models.SET_NULL, blank=True, null=True)
    
    class Meta:
        verbose_name = 'Programa de desarrollo'
        verbose_name_plural = 'Programas de desarrollo' 
        ordering = ['nombreprog']   
        db_table ='progdesarrollo'
    
    def __str__(self) :
        return self.nombreprog

class EntidActor(models.Model):
    idactor = models.AutoField(primary_key=True)
    nombreactor = models.CharField(max_length=100, verbose_name="Nombre de Entidad-Organización-Actor", null=False, blank=False, unique=True)
    nombrecorto = models.CharField(max_length=20, verbose_name="Nombre corto o Siglas de Entidad-Actor", unique=True)
    tipoactor = models.CharField(max_length=3, choices=ctiporg, null=False, default='GUB')
    pais = models.CharField(max_length=100, choices=cpais, verbose_name="País procedencia de la entidad")
    alcanc = models.CharField(max_length=10, choices=calcanc, verbose_name="Alcance del SIGC", null=False, default='Municipal')
    prgdesarr = models.ManyToManyField("ProgDesarrollo", verbose_name ="Programa(s) de desarrollo que ejecuta", related_name="programas")
    coordinador = models.ForeignKey("Usuario", verbose_name="Coordinador o representante principal", on_delete=models.SET_NULL, null=True, blank=True)
    altinfluenc = models.BooleanField(default=False, verbose_name="Alta Influencia")
    bajdepend = models.BooleanField(default=False, verbose_name="Baja dependencia")    
    munic = models.ForeignKey("Municipio", verbose_name="Municipio de la Entidad-Actor", on_delete=models.CASCADE, null=True, blank=True)

psigc/psigchom/templates/psigchom/MenuBar.html
<div id="nav">
    <ul class="sf-menu dropdown"> 
        <li class="{% if request.path == '/' %}selected{% endif %}"><a class="has_submenu" href="/">INICIO</a>
            <ul>   
                {% if not user.is_authenticated %}
                    <li class="{% if 'url_registuser' in request.path %}selected{% endif %}"><a href="{% url 'url_registuser' %}">Registrarse en el sitio</a></li>
                    <li class="{% if 'url_loginuser' in request.path %}selected{% endif %}"><a href="{% url 'url_loginuser' %}">Iniciar sesión de usuario</a></li>
                    <li><a>_________________</a></li>
                {% endif %}    
                <li class="{% if 'url_ayuda' in request.path %}selected{% endif %}"><a href="{% url 'url_ayuda' %}">Ayuda</a></li>
                <li class="{% if 'url_codigo' in request.path %}selected{% endif %}"><a href="{% url 'url_codigo' %}">Código de ética</a></li>
                {% if user.is_authenticated %}
                    <li class="{% if 'url_logout' in request.path %}selected{% endif %}"><a href="{% url 'url_logout' %}">finalizar sesión</a></li>
                {% endif %}      
                {% if not user.is_authenticated %}
                    <li class="{% if 'url_contacto' in request.path %}selected{% endif %}"><a href="{% url 'url_contacto' %}">Contactar</a></li>
                {% endif %}      
            </ul>  
        </li> 
        <li class="{% if 'url_redconoc' in request.path %}selected{% endif %}"><a class="has_submenu" href="{% url 'url_redconoc' %}">Red del Conocimiento</a>
            <ul>
                <li class="{% if 'url_noticia' in request.path %}selected{% endif %}"><a href="{% url 'url_noticia' %}">Noticias</a></li>
                <li class="{% if 'url_evento' in request.path %}selected{% endif %}"><a href="{% url 'url_evento' %}">Eventos</a></li>
                <li class="{% if 'url_documento' in request.path %}selected{% endif %}"><a href="{% url 'url_documento' %}">Documentos</a></li>
                <li class="{% if 'url_foro' in request.path %}selected{% endif %}"><a href="{% url 'url_foro' %}">Foros de debate</a></li>
                <li><a>_________________</a></li>
                <li class="{% if 'url_areasconoc' in request.path %}selected{% endif %}"><a href="{% url 'url_areasconoc' %}">Areas del conocimiento</a></li>
                <li class="{% if 'url_expertos' in request.path %}selected{% endif %}"><a href="{% url 'url_expertos' %}">Expertos-Consultores</a></li>
                {% if user.is_authenticated %}
                    <li><a>_________________</a></li>
                    <li class="{% if 'url_demanda' in request.path %}selected{% endif %}"><a href="{% url 'url_demanda' %}">Demanda</a></li>
                {% endif %} 
            </ul>
        </li>
        {% if user.is_authenticated %}
            <li class="{% if 'url_reportes' in request.path %}selected{% endif %}"><a class="has_submenu" href="#">Reportes</a>
                <ul>
                    <li class="{% if 'url_general' in request.path %}selected{% endif %}"><a href="{% url 'url_general' %}">Generalidades</a></li>
                    <li><a>_________________</a></li>
                    <li class="{% if 'url_indproyreg' in request.path %}selected{% endif %}"><a href="{% url 'url_indentidactreg' %}">Indicadores</a></li>
                    <li class="{% if 'url_evalproyreg' in request.path %}selected{% endif %}"><a href="{% url 'url_evalentidactreg' %}">Evaluaciones</a></li>
                    <!--li class="{% if 'url_conocasist' in request.path %}selected{% endif %}"><a href="{% url 'url_conocasist' %}">Conocimiento asistido</a></li-->
                </ul>
            </li>
                <li class="{% if 'url_basesdatos' in request.path %}selected{% endif %}" ><a class="has_submenu" href="{% url 'url_basesdatos' %}">Datos</a>
                    <ul>
                        <li class="{% if 'url_ejesbd' in request.path %}selected{% endif %}"><a href="{% url 'url_ejesbd' %}">Ejes</a></li>
                        <li><a>_________________</a></li>
                        <li class="{% if 'url_oacebd' in request.path %}selected{% endif %}"><a href="{% url 'url_oacebd' %}">Organismos del estado</a></li>
                        <li class="{% if 'url_progdesabd' in request.path %}selected{% endif %}"><a href="{% url 'url_progdesabd' %}">Programas de desarrollo</a></li>
                        <li class="{% if 'url_entidactbd' in request.path %}selected{% endif %}"><a href="{% url 'url_entidactbd' %}">Entidad-Actor</a></li>
                        <!--li class="{% if 'url_proyinvestbd' in request.path %}selected{% endif %}"><a href="">Proyectos de investigación</a></li-->
                        <li><a>_________________</a></li>
                        <li class="{% if 'url_usuariobd' in request.path %}selected{% endif %}"><a href="{% url 'url_usuariobd' %}">Usuarios</a></li>
                    </ul>
                </li>
            
                    <li class="{% if 'url_gestion' in request.path %}selected{% endif %}"><a class="has_submenu" href="{% url 'url_gestion' %}">Gestion</a>
                        <ul>
                            <li class="{% if 'url_noticiabd' in request.path %}selected{% endif %}"><a href="{% url 'url_noticiabd' %}">Noticias</a></li>
                            <li class="{% if 'url_eventobd' in request.path %}selected{% endif %}"><a href="{% url 'url_eventobd' %}">Eventos</a></li>
                            <li class="{% if 'url_documentobd' in request.path %}selected{% endif %}"><a href="{% url 'url_documentobd' %}">Documentos</a></li>   
                            <li class="{% if 'url_forobd' in request.path %}selected{% endif %}"><a href="{% url 'url_forobd' %}">Foros</a></li>
                            <li><a>_________________</a></li>
                            <li class="{% if 'url_areaconocbd' in request.path %}selected{% endif %}"><a href="{% url 'url_areaconocbd' %}">Áreas de Conocimiento</a></li>
                            <!--li class="{% if 'url_expertosbd' in request.path %}selected{% endif %}"><a href="{% url 'url_expertosbd' %}">Experticia</a></li-->
                            
                        </ul>
                    </li>

           
        {% endif %} 
        <h4>Buscar en el sitio</h4>
        <form action="" method="POST">
            <input type="text" id="searchquery" style="width: 200px" name="searchterm" />
            <input type="submit" id="searchbutton" value="Buscar" class ="btn btn-success" />
        </form>
    </ul>   
</div>

psigc/psigchom/templates/psigchom/SlideContainer.html
 
{% load static %}


<div id="slides-container">
    <div id="slides" >
        <div>
            <div class="slide-image"><img src="{% static 'psigchom/images/SAS-logo.png' %}" alt="Logo del SAS"/></div>
            <div class="slide-text">
                <h2>Soberania Alimentaria Sostenible</h2>
                <p>Apoyo estratégico a la seguridad alimentaria sostenible en Cuba. Nutrirnos desde lo local, nutrinos con soberanía</p>
            </div>
        </div>
        <div>
            <div class="slide-image"><img src="{% static 'psigchom/images/COSAS-logo.png' %}" alt="Logo del CONSAS" /></div>
            <div class="slide-text">
           	    <p>Fortalecimiento del Sistema Integrado de Gestión del</p>
                <h2>Conocimiento para la Seguridad Alimentaria Sostenible.</h2>
            </div>    
        </div>
        <div>
            <div class="slide-image slide-image-right"><img src="{% static 'psigchom/images/Ausp-logos.png' %}" alt="Logos auspicio" /></div>
            <div class="slide-text">
           	    <h2></h2>
                <p> </p>
            </div>   
        </div>
    </div>
    <div class="controls">
        <span class="jFlowNext"><span>Next</span></span>
        <span class="jFlowPrev"><span>Prev</span></span>
    </div>  
    <div id="myController">
        <span class="jFlowControl">Slide 1</span>
        <span class="jFlowControl">Slide 1</span>
        <span class="jFlowControl">Slide 1</span>
    </div> 
</div>

psigc/psigchom/templates/psigchom/contacto.html
{% extends 'psigchom/base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

  <div id="sub-header">
   <h2>Envíenos un mensaje contacto con sus opiniones, sugerencias o dudas</h2><h5>Ayúdenos a perfeccionar el software</h4>
  </div>
  <div id="breadcrumbs">
    <span>Ud. está aquí: </span><a href="/">INICIO</a> &raquo;&nbsp;<strong> Contacto</strong>
  </div>
  <div id="content">
    <div class="card shadow mb-4" style="width: 70%; padding: 1px 0px; margin: 10px auto;">
      <div class="card-body">
        <h4 class="card-title" style="align: center;" aria-hidden="true"><strong>Formulario para enviar mensaje de contacto</strong></h4>
        {% if messages %}
          {% for msg in messages %}
            <div class="alert alert-{{msg.tags}}" role="alert">{{msg}}</div>
          {% endfor %}
        {% endif%}     
        <form action="" method="POST" id="contactform" getmunicip-url="{% url 'url_getmunicipios' %}"> 
          {% csrf_token %}
          <div class="content" style="width:98%; padding: 0px 5px 5px" aling="center">
            <div class="row">
              {{contactForm.nombre.label}} 
              {{contactForm.nombre }}
            </div></br>
            <div class="row">
              <div class="col-lg-6">
                  {{procedenForm.provincia.label}}</br>
                  <select id="id_provincia" class="form-control select2" required="True">
                    <option disabled selected="true" value="0">--Seleccione una provincia--</option>
                    {% for prov in providata %}
                      <option value="{{prov.idprov}}">{{prov.nombreprov}}</option> 
                    {% endfor %}                    
                  </select>    
              </div>
              <div class="col-lg-6">
                    {{procedenForm.municipio.label}} 
                    <select name="municipio" id="id_municipio" class="form-control"  required="True">
                      <option disabled selected="true" value="0">--Seleccione un municipio--</option>
                      {% for munic in municipdata %}
                        <option value="{{munic.idmunicipio}}" data-chained="{{munic.provincia.idprov}}">{{munic.nombremunicip }}</option> 
                      {% endfor %}  
                    </select>   
              </div>
            </div></br>
            <div class="row">
              {{contactForm.ecorreo.label}} 
              {{contactForm.ecorreo }}
            </div></br>
            <div class="row">
              {{contactForm.asunto.label}} 
              {{contactForm.asunto }}
            </div></br>
            <div class="row">
              {{contactForm.contenido.label}} 
              {{contactForm.contenido }}
            </div></br>
          </div>  
          <p> (*) campo requerido </p>
          <button class="btn btn-success" type="submit" style="width: 150px; margin: 20px 100px;">ENVIAR</button>
        </form>           
      </div>
    </div><br>    
  </div>      
 
{%endblock%}

psigc/psigchom/templates/psigchom/main.html
{% extends 'psigchom/base.html' %}

{% load static %}

psigc/psigchom/templates/psigchom/municipioselec.html
{% load static %}
<link rel="stylesheet" href="{% static 'psigchom/css/bootstrap.min.css' %}" type="text/css">

<br>
<select id="id_provincia" name="provincia">
    {% for provincia in provincias %}
        <option value="{{ provincia.idprov }}">{{ provincia.nombreprov }}</option>
    {% endfor %}
</select><p></p>

<select id="id_municipio" name="municipio">
    <option value="">---------</option>
</select>

<script>
    $(document).ready(function() {
        $('#id_provincia').change(function() {
            var provId = $(this).val();
            $.ajax({
                url: '{% url "url_getmunics" %}',
                data: {'provId': provId},
                dataType: 'json',
                success: function(data) {
                    var municipios = data.municipios;
                    var municipiosSelect = $('#id_municipio');
                    municipiosSelect.empty();
                    municipiosSelect.append($('<option>').text('---------').attr('value', ''));
                    $.each(municipios, function(i, municipio) {
                        municipiosSelect.append($('<option>').text(municipio.nombremun).attr('value', municipio.idmun));
                    });
                }
            });
        });
    });
</script>

psigc/psigchom/templates/psigchom/noheaderpage.html
{% extends 'psigchom/main.html' %}

psigc/psigchom/templates/psigchom/procedencia.html
{% extends 'psigchom/base.html' %}


{% block css %}  
  {% load static %}
    <link rel="stylesheet" href="{% static 'psigchom/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'psigchom/css/select2.min.css' %}" type="text/css">

    <link rel="stylesheet" href="{% static 'psigchom/styles.css' %}" type="text/css" />
{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
  <div id="sub-header">
   <h2>Envíenos un mensaje contacto con sus opiniones, sugerencias o dudas</h2><h5>Ayúdenos a perfeccionar el software</h4>
  </div>
  <div id="breadcrumbs">
    <span>Ud. está aquí: </span><a href="/">INICIO</a> &raquo;&nbsp;<strong> Procedencia</strong>
  </div>
  <div id="content">
    <div class="row">
      <div class="col-lg-6">
          {{procedenForm.provincia.label}}</br>
          <select id="id_provincia" class="form-control select2" required="True">
            <option disabled selected="true" value="0">--Seleccione una provincia--</option>
            {% for prov in providata %}
              <option value="{{prov.idprov}}">{{prov.nombreprov}}</option> 
            {% endfor %}                    
          </select>    
      </div>
      <div class="col-lg-6">
          {{procedenForm.municipio.label}} 
          <select id="id_municipio" class="form-control select2"  required="True">
            <option disabled selected="true" value="0">--Seleccione un municipio--</option>
            {% for munic in municipdata %}
              <option value="{{munic.idmun}}" data-chained="{{munic.prov_id}}">{{munic.nombremun }}</option> 
            {% endfor %}  
          </select>   
      </div>
    </div><br>
    <!--form action="" method="POST" id="contactForm" getmunicipurl="{% url 'url_getmunicipios' %}"> 
      {% csrf_token %}  
      {{procedenForm.as_table}}
      <p> (*) campo requerido </p>
          <button class="btn btn-success" type="submit" style="width: 150px; margin: 20px 100px;">ENVIAR</button>
    </form-->
  </div>  
{% endblock %}

{% block js %}  

  <script type="text/javascript" src="{% static 'psigchom/js/jquery.js' %}"></script>
  <script type="text/javascript" src="{% static 'psigchom/js/select2.min.js' %}"></script>
  
  <script>
     S('#id_provincia').select2();
  </script>
  <script>
    $(docuemnt).change(function(){
      $("#id_provincia").change(function(){
        const url=$("#contacForm").attr("getmunicipurl");
        const provid=$(this).val();
        $.ajax({
          url: url,
          data: { 'prov_id': provid },
          success: function(data){
          $("#id_municipio").html(data);
          }
        });
      });
    });  


</script>

{% endblock %}

<!--script>

  $(function(){
    $("#id_municipio").chained("#id_provincia");
  });

</script-->

<!--script>

  $('.select2').select2({
      theme:"boostrap"
  });

</script-->      

<!--script>

  $.fn.select2.default.set()

</script-->


<!--script>

  $(document).ready(function(){
    var $provId=$("#id_provincia");
    var $muniId=$("#id_municipio");
    var $options=$muniId.find('option');
        $provId.('change', function(){
          $muniId.html($options.filter('[value="'+this.value+'"]'));
        }).trigger('change');
  });

</script-->  